app/models/__init__.py
from .user import User
from .user import *

app/models/user.py
from sqlalchemy.schema import Column, Index
from sqlalchemy.types import Integer, String, Text, TIMESTAMP,VARCHAR
from sqlalchemy.dialects.mysql import TINYINT
from app import app, db
from flask_login import UserMixin
import hashlib

class User(db.Model, UserMixin):
  __tablename__ = 'user'
  id = Column(Integer, primary_key=True)
  username = Column(String(255), nullable=False)
  truename = Column(String(255), nullable=False)
  password = Column(String(64), nullable=False)
  email = Column(String(255), nullable=False, unique=True)
  role = Column(TINYINT(2), nullable=False)
  created = Column(TIMESTAMP, nullable=False, server_default='0000-00-00 00:00:00')
  def __init__(self, username, truename, password, email, role, created):
    self.username = username
    self.truename = truename
    self.password = password
    self.email = email
    self.role = role
    self.created = created

  def is_authenticated(self):
    return True

  def is_active(self):
    return True

  def is_anonymous(self):
    return False

  def get_id(self):
    return self.id

  def __repr__(self):
    return '<User %r>' % (self.email)

  def md5_email(self):
    m = hashlib.md5()
    m.update(self.email)
    return m.hexdigest()

app/__init__.py
from flask import Flask
from flask.ext.sqlalchemy import SQLAlchemy
import sys
import logging

app = Flask(__name__)
app.config.from_object('config')

reload(sys)
sys.setdefaultencoding('utf-8')

db=SQLAlchemy(app)

logger = logging.getLogger()
logger.setLevel(app.config['LOGGING_LEVEL'])

# create console handler and set level to debug
hander = logging.StreamHandler()
hander.setLevel(app.config.get('LOGGING_LEVEL'))

formatter = logging.Formatter(app.config['LOGGING_FORMAT'])
hander.setFormatter(formatter)
logger.addHandler(hander)

app/views/__init__.py
# -*- coding: utf-8 -*-


from .user import user
from .public import public
from .birthday import birthday

from .user import *
from .public import *
from .errors import *
from .birthday import *

app/views/birthday.py
# -*- coding: utf-8 -*-
from app import app
from flask import Blueprint, render_template, request, url_for, make_response
from flask_login import login_user, logout_user, login_required,current_user

birthday = Blueprint('birthday', __name__)

@birthday.route('/')
@login_required
def list():
  return render_template("birthday/list.html", text="Hello guys")

app/views/errors.py
# -*- coding: utf-8 -*-

from flask import render_template
from app import app

@app.errorhandler(404)
def page_not_found(e):
  return render_template('404.html'), 404

@app.errorhandler(500)
def internal_server_error(e):
  return render_template('500.html'), 500

app/views/public.py
# -*- coding: utf-8 -*-
from app import app
from flask import Blueprint, render_template, request, url_for, make_response
from flask.ext.login import login_user, logout_user, login_required,current_user

public = Blueprint('public', __name__)

@public.route("/")
@login_required
def index():
  return render_template("index.html", text="Hello World")

app/views/user.py
# -*- coding: utf-8 -*-

from app import app, db, logger
from flask import render_template, Blueprint, redirect, json, request, make_response, url_for, g
from flask_login import login_user, logout_user, login_required, current_user
from app.models.user import User
from sqlalchemy import and_

user = Blueprint('user', __name__)

@user.route('/login', methods = ['GET', 'POST'])
def login():
  import hashlib
  if request.method == 'GET':
     return render_template("login.html")

  email = request.form["email"]
  password = request.form["password"]

  m = hashlib.md5()
  m.update(password)

  userinfo = User.query.filter(User.email == email).first()
  if userinfo is None:
    msg = '用户不存在, 请先注册'
    logger.info(msg)
    return render_template("login.html", email = email, msg = msg)

  userinfo = User.query.filter(and_(User.email == email, User.password == m.hexdigest())).first()
  if userinfo is None:
    msg = '用户名密码不正确'
    password = ''
    return render_template("login.html", email = email, password = password, msg = msg)
  else:
    """do nothing"""

  print 'login successful'
  response = make_response(redirect('/'))
  secure_token = create_token(userinfo.id, userinfo.email, request.user_agent)

  response.set_cookie('secure_token', value=secure_token, max_age=2592000)
  login_user(userinfo)
  return response


def create_token(id, email, useragent):
  import hashlib
  import base64
  m = hashlib.md5()
  m.update(str(id) + email + str(useragent))
  return m.hexdigest() + '_' + base64.b64encode(str(id))

def match_user_cookie(secure_cookie, useragent):
  tokens = secure_cookie.split('_')
  import base64
  id = base64.b64decode(tokens[1])
  user = User.query.filter(User.id == int(id)).first()
  if user:
    confirm_secure = create_token(user.id, user.email, useragent)
    if secure_cookie == confirm_secure:
      return user.id
  return None

@user.route('/logout')
@login_required
def logout():
  logout_user()
  response = make_response(redirect('/'))
  response.set_cookie('secure_token', '', 0);
  return response

app/views/views.py
from app import app
from flask import render_template

@app.route('/')
def index():
  return render_template("index.html", text="Hello World")

app/templates/birthday/list.html
{% extends "layout.html" %}
{% block head %}
    <link rel="stylesheet" href="/static/js/adminlte/dist/css/skins/_all-skins.min.css">
    <!-- daterange picker -->
    <link rel="stylesheet" href="/static/js/adminlte/plugins/daterangepicker/daterangepicker-bs3.css">
    <link rel="stylesheet" href="/static/js/adminlte/plugins/datepicker/datepicker3.css">
{% endblock %}
{% block body %}
  <!-- Content Header (Page header) -->
  <section class="content-header">
    <h1>
      BIRTHDAY
      <small></small>
    </h1>
    <!--
    <ol class="breadcrumb">
      <li><a href="#"><i class="fa fa-dashboard"></i> Level</a></li>
      <li class="active">Here</li>
    </ol>
    -->
  </section>

  <!-- Main content -->
  <section class="content">
    <!-- Your Page Content Here -->
    <div class="row">
      <div class="col-md-12">
        <div class="box">
          <div class="box-header">
            <form>
              <div class="row">
                <div class="col-md-3">
                  <div class="form-group">
                    <label>Sex</label>
                    <select aria-hidden="true" tabindex="-1" class="form-control select2 select2-hidden-accessible" style="width: 100%;">
                      <option selected="selected" value="-1">all</option>
                      <option value="1">male</option>
                      <option value="2">female</option>
                    </select>
                  </div>
                </div>
                <div class="col-md-3">
                  <div class="form-group">
                    <label>Status</label>
                    <select aria-hidden="true" tabindex="-1" class="form-control select2 select2-hidden-accessible" style="width: 100%;">
                      <option selected="selected" value="-1">all</option>
                      <option value="1">valid</option>
                      <option value="2">invalid</option>
                    </select>
                  </div>
                </div>
                <div class="col-md-4">
                  <div class="form-group">
                    <label>&nbsp;</label>
                    <div class="input-group">
                      <input class="form-control" placeholder="place enter user name" type="text">
                      <span class="input-group-btn">
                        <button class="btn btn-info btn-flat" type="button">Go!</button>
                      </span>
                    </div>
                  </div>
                </div>
                <div class="col-md-2">
                  <div class="form-group" style="margin-top: 25px; margin-left: 30%;">
                    <a href="#modal" data-toggle="modal" class="btn bg-olive">New <i class="fa fa-plus"></i></a>
                  </div>
                </div>
              </div>
            </form>
          </div>
          <div class="box-body no-padding">
            <table class="table table-striped">
              <tbody>
                <tr>
                 <th>#</th>
                 <th>Name</th>
                 <th>Sex</th>
                 <th>Birthday</th>
                 <th>Phone</th>
                 <th>Email</th>
                 <th>Status</th>
                  <th>Operate</th>
                </tr>
                <tr>
                  <td>1.</td>
                  <td>saboloh</td>
                  <td><i class="ion-male text-green"></i> male</td>
                  <td>0101</td>
                  <td>18600001111</td>
                  <td>leyu1992@126.com</td>
                  <td>有效</td>
                  <td>修改/删除</td>
                </tr>
                <tr>
                  <td>2.</td>
                  <td>cara</td>
                  <td><i class="ion-female text-red"></i> female</td>
                  <td>0101</td>
                  <td>18600001111</td>
                  <td>leyu1992@126.com</td>
                  <td>有效</td>
                  <td>修改/删除</td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </section><!-- /.content -->

  <!-- add/edit user modal -->
  <div class="modal fade" tabindex="-1" role="dialog" id="modal">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span></button>
          <h4 class="modal-title">Modal Default</h4>
        </div>
        <div class="modal-body">
          <form class="form-horizontal">
            <div class="box-body">
              <div class="form-group">
                <label for="username" class="col-sm-2 control-label">Name</label>
                <div class="col-sm-10">
                  <input type="text" class="form-control" name="username" placeholder="Username">
                </div>
              </div>
              <div class="form-group">
                <label for="sex" class="col-sm-2 control-label">Sex</label>
                <div class="col-sm-10">
                  <div class="radio">
                    <label>
                      <input type="radio" name="r3" checked> Male
                    </label>
                    &nbsp;&nbsp;
                    <label>
                      <input type="radio" name="r3"> Female
                    </label>
                  </div>
                </div>
              </div>
              <div class="form-group">
                <label for="inputEmail3" class="col-sm-2 control-label">Email</label>
                <div class="col-sm-10">
                  <input type="email" class="form-control" id="inputEmail3" placeholder="Email">
                </div>
              </div>
              <div class="form-group">
                <label for="phone" class="col-sm-2 control-label">Phone</label>
                <div class="col-sm-10">
                  <input type="text" class="form-control" placeholder="Phone">
                </div>
              </div>
              <div class="form-group">
                <label for="status" class="col-sm-2 control-label">Status</label>
                <div class="col-sm-10">
                  <div class="radio">
                    <label>
                      <input type="radio" name="r4" checked> valid
                    </label>
                    &nbsp;&nbsp;
                    <label>
                      <input type="radio" name="r4"> invalid
                    </label>
                  </div>
                </div>
              </div>
              <div class="form-group">
                <label for="birthday" class="col-sm-2 control-label">Birthday</label>
                <div class="col-sm-10">
                  <div class="input-group date">
                    <input type="text" id="date-group" class="form-control" placeholder="Birthday"/>
                    <span class="input-group-addon">
                      <i class="fa fa-calendar"></i>
                    </span>
                  </div>
                </div>
              </div>
            </div><!-- /.box-body -->
          </form>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default pull-left" data-dismiss="modal">Close</button>
          <button type="button" class="btn btn-primary">Save changes</button>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

{% block footer %}
    <script src="/static/js/adminlte/plugins/iCheck/icheck.min.js"></script>
    <!-- date-range-picker -->
    <script src="/static/js/moment/moment.js"></script>
    <script src="/static/js/adminlte/plugins/daterangepicker/daterangepicker.js"></script>
    <script src="/static/js/adminlte/plugins/datepicker/bootstrap-datepicker.js"></script>
    <script src="/static/js/adminlte/plugins/datepicker/locales/bootstrap-datepicker.zh-CN.js"></script>
    <script src="/static/js/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="/static/js/jquery-validation/dist/additional-methods.min.js"></script>
    <script>
      $('#date-group').daterangepicker({
        timePicker: false,
        singleDatePicker: true,
        "showDropdowns": true,
        format : 'YYYY-MM-DD'
      });
    </script>
{% endblock %}

app/templates/index.html
{% extends "layout.html" %}
{% block body %}
  <!-- Content Header (Page header) -->
  <section class="content-header">
    <h1>
      Blessing
      <small></small>
    </h1>
    <!--
    <ol class="breadcrumb">
      <li><a href="#"><i class="fa fa-dashboard"></i> Level</a></li>
      <li class="active">Here</li>
    </ol>
    -->
  </section>

  <!-- Main content -->
  <section class="content">
    <!-- Your Page Content Here -->
    {{ text }}
  </section><!-- /.content -->
{% endblock %}

app/templates/login.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Blessing | Log in</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
  <!-- Bootstrap 3.3.6 -->
  <link rel="stylesheet" href="/static/js/adminlte/bootstrap/css/bootstrap.min.css">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="/static/js/fontawesome/css/font-awesome.min.css">
  <!-- Ionicons -->
  <link rel="stylesheet" href="/static/js/ionicons/css/ionicons.min.css">
  <!-- Theme style -->
  <link rel="stylesheet" href="/static/js/adminlte/dist/css/AdminLTE.min.css">
  <!-- iCheck -->
  <link rel="stylesheet" href="/static/js/adminlte/plugins/iCheck/square/blue.css">
  <!-- login -->
  <link rel="stylesheet" href="/static/css/login.css">

  <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}">
  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->
</head>
<body class="hold-transition login-page">
<div class="login-box">
  <div class="login-logo">
    <a href="../../index2.html"><b>Blessing</b></a>
  </div>
  <!-- /.login-logo -->
  <div class="login-box-body">
    <p class="login-box-msg">Sign in to start your session</p>

    <form action="{{ url_for('user.login') }}" method="post">
      <div class="form-group has-feedback">
        <input type="email" name="email" value="{{ email }}" class="form-control" placeholder="Email">
        <span class="glyphicon glyphicon-envelope form-control-feedback"></span>
      </div>
      <div class="form-group has-feedback">
        <input type="password" name="password" value="{{ password }}" class="form-control" placeholder="Password">
        <span class="help-block text-red">{{msg}}</span>
        <span class="glyphicon glyphicon-lock form-control-feedback"></span>
      </div>

      <div class="row">
        <div class="col-xs-8">
          <div class="checkbox icheck">
            <label>
              <input type="checkbox" name="remember"> Remember Me
            </label>
          </div>
        </div>
        <!-- /.col -->
        <div class="col-xs-4">
          <button type="submit" class="btn btn-primary btn-block btn-flat">Sign In</button>
        </div>
        <!-- /.col -->
      </div>
    </form>

    <div class="social-auth-links text-center">
      <p>- OR -</p>
      <a href="#" class="btn btn-block btn-social btn-facebook btn-flat"><i class="fa fa-facebook"></i> Sign in using
        Facebook</a>
      <a href="#" class="btn btn-block btn-social btn-google btn-flat"><i class="fa fa-google-plus"></i> Sign in using
        Google+</a>
    </div>
    <!-- /.social-auth-links -->

    <a href="#">I forgot my password</a><br>
    <a href="register.html" class="text-center">Register a new membership</a>

  </div>
  <!-- /.login-box-body -->
</div>
<!-- /.login-box -->

<!-- jQuery  -->
<script src="/static/js/jquery/dist/jquery.min.js"></script>
<!-- Bootstrap 3.3.5 -->
<script src="/static/js/adminlte/bootstrap/js/bootstrap.min.js"></script>
<!-- iCheck -->
<script src="/static/js/adminlte/plugins/iCheck/icheck.min.js"></script>
<script>
  $(function () {
    $('input').iCheck({
      checkboxClass: 'icheckbox_square-blue',
      radioClass: 'iradio_square-blue',
      increaseArea: '20%' // optional
    });
  });
</script>
</body>
</html>